services:
  master:
    build:
      context: .
      dockerfile: Dockerfile
    image: mpi-distributed-search:latest
    container_name: mpi-master
    working_dir: /app
    volumes:
      - ./:/app
    tty: true
    stdin_open: true
    command: /usr/sbin/sshd -D
    networks:
      - frontend_net
      - compute_net

  worker:
    image: mpi-distributed-search:latest
    depends_on:
      - master
    working_dir: /app
    volumes:                # <-- ADD THIS
      - ./:/app             # <-- ADD THIS
    tty: true
    stdin_open: true
    command: /usr/sbin/sshd -D
    networks:
      - compute_net

networks:
  frontend_net:
    driver: bridge
  compute_net:
    driver: bridge
    internal: true